# Generated by Django 4.2 on 2023-04-16 17:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('teams', '0004_team_player'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='team',
            name='player',
        ),
    ]
