# Generated by Django 4.2 on 2023-04-17 16:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('teams', '0005_remove_team_player'),
    ]

    operations = [
        migrations.RenameField(
            model_name='team',
            old_name='shirt_image',
            new_name='logo',
        ),
    ]
