# Generated by Django 4.2 on 2023-04-16 04:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='shirt_image',
        ),
        migrations.AddField(
            model_name='user',
            name='budget',
            field=models.FloatField(default=60.0),
        ),
    ]
