# Generated by Django 4.2 on 2023-04-17 09:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('info', '0002_info_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='info',
            name='gw_points',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='info',
            name='total_points',
            field=models.IntegerField(default=0),
        ),
    ]
