# Generated by Django 4.2 on 2023-04-17 12:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('info', '0003_info_gw_points_info_total_points'),
    ]

    operations = [
        migrations.AlterField(
            model_name='info',
            name='budget',
            field=models.FloatField(default=65),
        ),
    ]
