# Generated by Django 4.2 on 2023-04-16 15:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Player',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('position', models.CharField(max_length=2)),
                ('price', models.FloatField()),
                ('week_points', models.IntegerField()),
                ('total_points', models.IntegerField()),
            ],
        ),
    ]
