# Generated by Django 4.2 on 2023-04-16 16:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('players', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='player',
            old_name='week_points',
            new_name='gw_points',
        ),
    ]
