# Generated by Django 4.2 on 2023-04-16 17:36

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('players', '0004_alter_player_team'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='users',
            field=models.ManyToManyField(related_name='selected_players', to=settings.AUTH_USER_MODEL),
        ),
    ]
